# Regenerates app/src/main/cpp/shader_effects_spv.h from the GLSL sources in
# this directory. Run manually when present_effects.{vert,frag} change; the
# Android build itself only consumes the checked-in header.

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$out = Join-Path $here "..\shader_effects_spv.h"

$glslcCandidates = @(
    "$env:LOCALAPPDATA\Android\Sdk\ndk\28.2.13676358\shader-tools\windows-x86_64\glslc.exe",
    "$env:LOCALAPPDATA\Android\Sdk\ndk\29.0.13113456\shader-tools\windows-x86_64\glslc.exe"
) + (Get-Command glslc -ErrorAction SilentlyContinue | ForEach-Object { $_.Source })

$glslc = $glslcCandidates | Where-Object { $_ -and (Test-Path $_) } | Select-Object -First 1
if (-not $glslc) {
    throw "glslc.exe not found. Install the NDK shader-tools or add glslc to PATH."
}

function Convert-ToHeader([string]$name, [string]$spvPath) {
    $bytes = [System.IO.File]::ReadAllBytes($spvPath)
    if ($bytes.Length % 4 -ne 0) { throw "SPIR-V size is not word aligned: $spvPath" }
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("static const uint32_t ${name}[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 4) {
        $word = [BitConverter]::ToUInt32($bytes, $i)
        $lines.Add(("    0x{0:x8}u," -f $word))
    }
    $lines.Add("};")
    $lines.Add("static const size_t ${name}_size_bytes = sizeof($name);")
    return $lines
}

$tmp = Join-Path $env:TEMP ("emucorer_spirv_" + [Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $tmp | Out-Null
try {
    $vertSpv = Join-Path $tmp "present_effects.vert.spv"
    $fragSpv = Join-Path $tmp "present_effects.frag.spv"
    & $glslc -fshader-stage=vert -o $vertSpv (Join-Path $here "present_effects.vert")
    if ($LASTEXITCODE -ne 0) { throw "glslc vertex compilation failed" }
    & $glslc -fshader-stage=frag -o $fragSpv (Join-Path $here "present_effects.frag")
    if ($LASTEXITCODE -ne 0) { throw "glslc fragment compilation failed" }

    $header = New-Object System.Collections.Generic.List[string]
    $header.Add("// Generated by shaders/regen_spirv.ps1 from present_effects.{vert,frag}. Do not edit.")
    $header.Add("#pragma once")
    $header.Add("#include <cstddef>")
    $header.Add("#include <cstdint>")
    $header.Add("")
    $header.AddRange([string[]](Convert-ToHeader "k_present_effects_vert_spv" $vertSpv))
    $header.Add("")
    $header.AddRange([string[]](Convert-ToHeader "k_present_effects_frag_spv" $fragSpv))
    $header.Add("")
    [System.IO.File]::WriteAllLines($out, $header)
    Write-Output "Wrote $out"
} finally {
    Remove-Item -Recurse -Force $tmp
}
