// SPDX-FileCopyrightText: 2026 SBRO
// SPDX-License-Identifier: LicenseRef-EmuCoreR-Proprietary
package com.sbro.emucorer.core

import com.sbro.emucorer.R

/**
 * Localized labels, descriptions and choice labels for the in-code SwanStation
 * core option catalogue in [SwanStationCoreOptions].
 */
object SwanStationCoreOptionStrings {
    val optionLabelRes: Map<String, Int> = buildMap {
        put("swanstation_Console_Region", R.string.ss_core_console_region)
        put("swanstation_BIOS_PathNTSCJ", R.string.ss_core_bios_pathntscj)
        put("swanstation_BIOS_PathNTSCU", R.string.ss_core_bios_pathntscu)
        put("swanstation_BIOS_PathPAL", R.string.ss_core_bios_pathpal)
        put("swanstation_BIOS_PatchFastBoot", R.string.ss_core_bios_patchfastboot)
        put("swanstation_CDROM_RegionCheck", R.string.ss_core_cdrom_regioncheck)
        put("swanstation_CDROM_ReadThread", R.string.ss_core_cdrom_readthread)
        put("swanstation_CDROM_LoadImagePatches", R.string.ss_core_cdrom_loadimagepatches)
        put("swanstation_CDROM_LoadImageToRAM", R.string.ss_core_cdrom_loadimagetoram)
        put("swanstation_CDROM_PreCacheCHD", R.string.ss_core_cdrom_precachechd)
        put("swanstation_CDROM_MuteCDAudio", R.string.ss_core_cdrom_mutecdaudio)
        put("swanstation_CDROM_ReadSpeedup", R.string.ss_core_cdrom_readspeedup)
        put("swanstation_CDROM_SeekSpeedup", R.string.ss_core_cdrom_seekspeedup)
        put("swanstation_CPU_ExecutionMode", R.string.ss_core_cpu_executionmode)
        put("swanstation_GPU_Renderer", R.string.ss_core_gpu_renderer)
        put("swanstation_GPU_ResolutionScale", R.string.ss_core_gpu_resolutionscale)
        put("swanstation_GPU_UseThread", R.string.ss_core_gpu_usethread)
        put("swanstation_GPU_UseSoftwareRendererForReadbacks", R.string.ss_core_gpu_usesoftwarerendererforreadbacks)
        put("swanstation_GPU_MSAA", R.string.ss_core_gpu_msaa)
        put("swanstation_GPU_TrueColor", R.string.ss_core_gpu_truecolor)
        put("swanstation_GPU_ScaledDithering", R.string.ss_core_gpu_scaleddithering)
        put("swanstation_GPU_DisableInterlacing", R.string.ss_core_gpu_disableinterlacing)
        put("swanstation_GPU_ForceNTSCTimings", R.string.ss_core_gpu_forcentsctimings)
        put("swanstation_Display_Force4_3For24Bit", R.string.ss_core_display_force4_3for24bit)
        put("swanstation_GPU_ChromaSmoothing24Bit", R.string.ss_core_gpu_chromasmoothing24bit)
        put("swanstation_GPU_TextureFilter", R.string.ss_core_gpu_texturefilter)
        put("swanstation_GPU_WidescreenHack", R.string.ss_core_gpu_widescreenhack)
        put("swanstation_GPU_PGXPEnable", R.string.ss_core_gpu_pgxpenable)
        put("swanstation_GPU_PGXPCulling", R.string.ss_core_gpu_pgxpculling)
        put("swanstation_GPU_PGXPTextureCorrection", R.string.ss_core_gpu_pgxptexturecorrection)
        put("swanstation_GPU_PGXPColorCorrection", R.string.ss_core_gpu_pgxpcolorcorrection)
        put("swanstation_GPU_PGXPDepthBuffer", R.string.ss_core_gpu_pgxpdepthbuffer)
        put("swanstation_GPU_PGXPVertexCache", R.string.ss_core_gpu_pgxpvertexcache)
        put("swanstation_GPU_PGXPCPU", R.string.ss_core_gpu_pgxpcpu)
        put("swanstation_GPU_PGXPPreserveProjFP", R.string.ss_core_gpu_pgxppreserveprojfp)
        put("swanstation_GPU_PGXPTolerance", R.string.ss_core_gpu_pgxptolerance)
        put("swanstation_GPU_PGXPDepthClearThreshold", R.string.ss_core_gpu_pgxpdepthclearthreshold)
        put("swanstation_Display_AspectRatio", R.string.ss_core_display_aspectratio)
        put("swanstation_Display_CustomAspectRatioNumerator", R.string.ss_core_display_customaspectrationumerator)
        put("swanstation_Display_CustomAspectRatioDenominator", R.string.ss_core_display_customaspectratiodenominator)
        put("swanstation_Display_CropMode", R.string.ss_core_display_cropmode)
        put("swanstation_GPU_DownsampleMode", R.string.ss_core_gpu_downsamplemode)
        put("swanstation_GPU_ShaderPrecompile", R.string.ss_core_gpu_shaderprecompile)
        put("swanstation_Display_ShowOSDMessages", R.string.ss_core_display_showosdmessages)
        put("swanstation_Display_ActiveStartOffset", R.string.ss_core_display_activestartoffset)
        put("swanstation_Display_ActiveEndOffset", R.string.ss_core_display_activeendoffset)
        put("swanstation_Display_LineStartOffset", R.string.ss_core_display_linestartoffset)
        put("swanstation_Display_LineEndOffset", R.string.ss_core_display_lineendoffset)
        put("swanstation_MemoryCards_Card1Type", R.string.ss_core_memorycards_card1type)
        put("swanstation_MemoryCards_Card2Type", R.string.ss_core_memorycards_card2type)
        put("swanstation_MemoryCards_UsePlaylistTitle", R.string.ss_core_memorycards_useplaylisttitle)
        put("swanstation_ControllerPorts_MultitapMode", R.string.ss_core_controllerports_multitapmode)
        put("swanstation_Controller_AnalogCombo", R.string.ss_core_controller_analogcombo)
        put("swanstation_Controller_EnableRumble", R.string.ss_core_controller_enablerumble)
        put("swanstation_Controller_ShowCrosshair", R.string.ss_core_controller_showcrosshair)
        put("swanstation_Controller1_ForceAnalog", R.string.ss_core_controller1_forceanalog)
        put("swanstation_Controller1_AnalogDPadInDigitalMode", R.string.ss_core_controller1_analogdpadindigitalmode)
        put("swanstation_Controller1_AxisScale", R.string.ss_core_controller1_axisscale)
        put("swanstation_Controller1_VibrationBias", R.string.ss_core_controller1_vibrationbias)
        put("swanstation_Controller1_XScale", R.string.ss_core_controller1_xscale)
        put("swanstation_Controller1_YScale", R.string.ss_core_controller1_yscale)
        put("swanstation_Controller1_SteeringDeadzone", R.string.ss_core_controller1_steeringdeadzone)
        put("swanstation_Controller1_TwistResponse", R.string.ss_core_controller1_twistresponse)
        put("swanstation_Controller2_ForceAnalog", R.string.ss_core_controller2_forceanalog)
        put("swanstation_Controller2_AnalogDPadInDigitalMode", R.string.ss_core_controller2_analogdpadindigitalmode)
        put("swanstation_Controller2_AxisScale", R.string.ss_core_controller2_axisscale)
        put("swanstation_Controller2_VibrationBias", R.string.ss_core_controller2_vibrationbias)
        put("swanstation_Controller2_XScale", R.string.ss_core_controller2_xscale)
        put("swanstation_Controller2_YScale", R.string.ss_core_controller2_yscale)
        put("swanstation_Controller2_SteeringDeadzone", R.string.ss_core_controller2_steeringdeadzone)
        put("swanstation_Controller2_TwistResponse", R.string.ss_core_controller2_twistresponse)
        put("swanstation_Controller3_ForceAnalog", R.string.ss_core_controller3_forceanalog)
        put("swanstation_Controller3_AnalogDPadInDigitalMode", R.string.ss_core_controller3_analogdpadindigitalmode)
        put("swanstation_Controller3_AxisScale", R.string.ss_core_controller3_axisscale)
        put("swanstation_Controller3_VibrationBias", R.string.ss_core_controller3_vibrationbias)
        put("swanstation_Controller3_SteeringDeadzone", R.string.ss_core_controller3_steeringdeadzone)
        put("swanstation_Controller3_TwistResponse", R.string.ss_core_controller3_twistresponse)
        put("swanstation_Controller4_ForceAnalog", R.string.ss_core_controller4_forceanalog)
        put("swanstation_Controller4_AnalogDPadInDigitalMode", R.string.ss_core_controller4_analogdpadindigitalmode)
        put("swanstation_Controller4_AxisScale", R.string.ss_core_controller4_axisscale)
        put("swanstation_Controller4_VibrationBias", R.string.ss_core_controller4_vibrationbias)
        put("swanstation_Controller4_SteeringDeadzone", R.string.ss_core_controller4_steeringdeadzone)
        put("swanstation_Controller4_TwistResponse", R.string.ss_core_controller4_twistresponse)
        put("swanstation_Controller5_ForceAnalog", R.string.ss_core_controller5_forceanalog)
        put("swanstation_Controller5_AnalogDPadInDigitalMode", R.string.ss_core_controller5_analogdpadindigitalmode)
        put("swanstation_Controller5_AxisScale", R.string.ss_core_controller5_axisscale)
        put("swanstation_Controller5_VibrationBias", R.string.ss_core_controller5_vibrationbias)
        put("swanstation_Controller6_ForceAnalog", R.string.ss_core_controller6_forceanalog)
        put("swanstation_Controller6_AnalogDPadInDigitalMode", R.string.ss_core_controller6_analogdpadindigitalmode)
        put("swanstation_Controller6_AxisScale", R.string.ss_core_controller6_axisscale)
        put("swanstation_Controller6_VibrationBias", R.string.ss_core_controller6_vibrationbias)
        put("swanstation_Controller7_ForceAnalog", R.string.ss_core_controller7_forceanalog)
        put("swanstation_Controller7_AnalogDPadInDigitalMode", R.string.ss_core_controller7_analogdpadindigitalmode)
        put("swanstation_Controller7_AxisScale", R.string.ss_core_controller7_axisscale)
        put("swanstation_Controller7_VibrationBias", R.string.ss_core_controller7_vibrationbias)
        put("swanstation_Controller8_ForceAnalog", R.string.ss_core_controller8_forceanalog)
        put("swanstation_Controller8_AnalogDPadInDigitalMode", R.string.ss_core_controller8_analogdpadindigitalmode)
        put("swanstation_Controller8_AxisScale", R.string.ss_core_controller8_axisscale)
        put("swanstation_Controller8_VibrationBias", R.string.ss_core_controller8_vibrationbias)
        put("swanstation_CDROM_ReadaheadSectors", R.string.ss_core_cdrom_readaheadsectors)
        put("swanstation_CPU_Overclock", R.string.ss_core_cpu_overclock)
        put("swanstation_Main_ApplyGameSettings", R.string.ss_core_main_applygamesettings)
        put("swanstation_Logging_LogLevel", R.string.ss_core_logging_loglevel)
        put("swanstation_CPU_RecompilerICache", R.string.ss_core_cpu_recompilericache)
        put("swanstation_CPU_RecompilerBlockLinking", R.string.ss_core_cpu_recompilerblocklinking)
        put("swanstation_CPU_FastmemMode", R.string.ss_core_cpu_fastmemmode)
        put("swanstation_CPU_FastmemRewrite", R.string.ss_core_cpu_fastmemrewrite)
        put("swanstation_TextureReplacements_EnableVRAMWriteReplacements", R.string.ss_core_texturereplacements_enablevramwritereplacements)
        put("swanstation_TextureReplacements_PreloadTextures", R.string.ss_core_texturereplacements_preloadtextures)
        put("swanstation_Main_RunaheadFrameCount", R.string.ss_core_main_runaheadframecount)
        put("swanstation_Console_Enable8MBRAM", R.string.ss_core_console_enable8mbram)
        put("swanstation_Hacks_OldMDECRoutines", R.string.ss_core_hacks_oldmdecroutines)
        put("swanstation_Audio_FastHook", R.string.ss_core_audio_fasthook)
    }

    val optionDescriptionRes: Map<String, Int> = buildMap {
        put("swanstation_Console_Region", R.string.ss_core_console_region_desc)
        put("swanstation_BIOS_PathNTSCJ", R.string.ss_core_bios_pathntscj_desc)
        put("swanstation_BIOS_PathNTSCU", R.string.ss_core_bios_pathntscu_desc)
        put("swanstation_BIOS_PathPAL", R.string.ss_core_bios_pathpal_desc)
        put("swanstation_BIOS_PatchFastBoot", R.string.ss_core_bios_patchfastboot_desc)
        put("swanstation_CDROM_RegionCheck", R.string.ss_core_cdrom_regioncheck_desc)
        put("swanstation_CDROM_ReadThread", R.string.ss_core_cdrom_readthread_desc)
        put("swanstation_CDROM_LoadImagePatches", R.string.ss_core_cdrom_loadimagepatches_desc)
        put("swanstation_CDROM_LoadImageToRAM", R.string.ss_core_cdrom_loadimagetoram_desc)
        put("swanstation_CDROM_PreCacheCHD", R.string.ss_core_cdrom_precachechd_desc)
        put("swanstation_CDROM_MuteCDAudio", R.string.ss_core_cdrom_mutecdaudio_desc)
        put("swanstation_CDROM_ReadSpeedup", R.string.ss_core_cdrom_readspeedup_desc)
        put("swanstation_CDROM_SeekSpeedup", R.string.ss_core_cdrom_seekspeedup_desc)
        put("swanstation_CPU_ExecutionMode", R.string.ss_core_cpu_executionmode_desc)
        put("swanstation_GPU_Renderer", R.string.ss_core_gpu_renderer_desc)
        put("swanstation_GPU_ResolutionScale", R.string.ss_core_gpu_resolutionscale_desc)
        put("swanstation_GPU_UseThread", R.string.ss_core_gpu_usethread_desc)
        put("swanstation_GPU_UseSoftwareRendererForReadbacks", R.string.ss_core_gpu_usesoftwarerendererforreadbacks_desc)
        put("swanstation_GPU_MSAA", R.string.ss_core_gpu_msaa_desc)
        put("swanstation_GPU_TrueColor", R.string.ss_core_gpu_truecolor_desc)
        put("swanstation_GPU_ScaledDithering", R.string.ss_core_gpu_scaleddithering_desc)
        put("swanstation_GPU_DisableInterlacing", R.string.ss_core_gpu_disableinterlacing_desc)
        put("swanstation_GPU_ForceNTSCTimings", R.string.ss_core_gpu_forcentsctimings_desc)
        put("swanstation_Display_Force4_3For24Bit", R.string.ss_core_display_force4_3for24bit_desc)
        put("swanstation_GPU_ChromaSmoothing24Bit", R.string.ss_core_gpu_chromasmoothing24bit_desc)
        put("swanstation_GPU_TextureFilter", R.string.ss_core_gpu_texturefilter_desc)
        put("swanstation_GPU_WidescreenHack", R.string.ss_core_gpu_widescreenhack_desc)
        put("swanstation_GPU_PGXPEnable", R.string.ss_core_gpu_pgxpenable_desc)
        put("swanstation_GPU_PGXPCulling", R.string.ss_core_gpu_pgxpculling_desc)
        put("swanstation_GPU_PGXPTextureCorrection", R.string.ss_core_gpu_pgxptexturecorrection_desc)
        put("swanstation_GPU_PGXPColorCorrection", R.string.ss_core_gpu_pgxpcolorcorrection_desc)
        put("swanstation_GPU_PGXPDepthBuffer", R.string.ss_core_gpu_pgxpdepthbuffer_desc)
        put("swanstation_GPU_PGXPVertexCache", R.string.ss_core_gpu_pgxpvertexcache_desc)
        put("swanstation_GPU_PGXPCPU", R.string.ss_core_gpu_pgxpcpu_desc)
        put("swanstation_GPU_PGXPPreserveProjFP", R.string.ss_core_gpu_pgxppreserveprojfp_desc)
        put("swanstation_GPU_PGXPTolerance", R.string.ss_core_gpu_pgxptolerance_desc)
        put("swanstation_GPU_PGXPDepthClearThreshold", R.string.ss_core_gpu_pgxpdepthclearthreshold_desc)
        put("swanstation_Display_AspectRatio", R.string.ss_core_display_aspectratio_desc)
        put("swanstation_Display_CustomAspectRatioNumerator", R.string.ss_core_display_customaspectrationumerator_desc)
        put("swanstation_Display_CustomAspectRatioDenominator", R.string.ss_core_display_customaspectratiodenominator_desc)
        put("swanstation_Display_CropMode", R.string.ss_core_display_cropmode_desc)
        put("swanstation_GPU_DownsampleMode", R.string.ss_core_gpu_downsamplemode_desc)
        put("swanstation_GPU_ShaderPrecompile", R.string.ss_core_gpu_shaderprecompile_desc)
        put("swanstation_Display_ShowOSDMessages", R.string.ss_core_display_showosdmessages_desc)
        put("swanstation_Display_ActiveStartOffset", R.string.ss_core_display_activestartoffset_desc)
        put("swanstation_Display_ActiveEndOffset", R.string.ss_core_display_activeendoffset_desc)
        put("swanstation_Display_LineStartOffset", R.string.ss_core_display_linestartoffset_desc)
        put("swanstation_Display_LineEndOffset", R.string.ss_core_display_lineendoffset_desc)
        put("swanstation_MemoryCards_Card1Type", R.string.ss_core_memorycards_card1type_desc)
        put("swanstation_MemoryCards_Card2Type", R.string.ss_core_memorycards_card2type_desc)
        put("swanstation_MemoryCards_UsePlaylistTitle", R.string.ss_core_memorycards_useplaylisttitle_desc)
        put("swanstation_ControllerPorts_MultitapMode", R.string.ss_core_controllerports_multitapmode_desc)
        put("swanstation_Controller_AnalogCombo", R.string.ss_core_controller_analogcombo_desc)
        put("swanstation_Controller_EnableRumble", R.string.ss_core_controller_enablerumble_desc)
        put("swanstation_Controller_ShowCrosshair", R.string.ss_core_controller_showcrosshair_desc)
        put("swanstation_Controller1_ForceAnalog", R.string.ss_core_controller1_forceanalog_desc)
        put("swanstation_Controller1_AnalogDPadInDigitalMode", R.string.ss_core_controller1_analogdpadindigitalmode_desc)
        put("swanstation_Controller1_AxisScale", R.string.ss_core_controller1_axisscale_desc)
        put("swanstation_Controller1_VibrationBias", R.string.ss_core_controller1_vibrationbias_desc)
        put("swanstation_Controller1_XScale", R.string.ss_core_controller1_xscale_desc)
        put("swanstation_Controller1_YScale", R.string.ss_core_controller1_yscale_desc)
        put("swanstation_Controller1_SteeringDeadzone", R.string.ss_core_controller1_steeringdeadzone_desc)
        put("swanstation_Controller1_TwistResponse", R.string.ss_core_controller1_twistresponse_desc)
        put("swanstation_Controller2_ForceAnalog", R.string.ss_core_controller2_forceanalog_desc)
        put("swanstation_Controller2_AnalogDPadInDigitalMode", R.string.ss_core_controller2_analogdpadindigitalmode_desc)
        put("swanstation_Controller2_AxisScale", R.string.ss_core_controller2_axisscale_desc)
        put("swanstation_Controller2_VibrationBias", R.string.ss_core_controller2_vibrationbias_desc)
        put("swanstation_Controller2_XScale", R.string.ss_core_controller2_xscale_desc)
        put("swanstation_Controller2_YScale", R.string.ss_core_controller2_yscale_desc)
        put("swanstation_Controller2_SteeringDeadzone", R.string.ss_core_controller2_steeringdeadzone_desc)
        put("swanstation_Controller2_TwistResponse", R.string.ss_core_controller2_twistresponse_desc)
        put("swanstation_Controller3_ForceAnalog", R.string.ss_core_controller3_forceanalog_desc)
        put("swanstation_Controller3_AnalogDPadInDigitalMode", R.string.ss_core_controller3_analogdpadindigitalmode_desc)
        put("swanstation_Controller3_AxisScale", R.string.ss_core_controller3_axisscale_desc)
        put("swanstation_Controller3_VibrationBias", R.string.ss_core_controller3_vibrationbias_desc)
        put("swanstation_Controller3_SteeringDeadzone", R.string.ss_core_controller3_steeringdeadzone_desc)
        put("swanstation_Controller3_TwistResponse", R.string.ss_core_controller3_twistresponse_desc)
        put("swanstation_Controller4_ForceAnalog", R.string.ss_core_controller4_forceanalog_desc)
        put("swanstation_Controller4_AnalogDPadInDigitalMode", R.string.ss_core_controller4_analogdpadindigitalmode_desc)
        put("swanstation_Controller4_AxisScale", R.string.ss_core_controller4_axisscale_desc)
        put("swanstation_Controller4_VibrationBias", R.string.ss_core_controller4_vibrationbias_desc)
        put("swanstation_Controller4_SteeringDeadzone", R.string.ss_core_controller4_steeringdeadzone_desc)
        put("swanstation_Controller4_TwistResponse", R.string.ss_core_controller4_twistresponse_desc)
        put("swanstation_Controller5_ForceAnalog", R.string.ss_core_controller5_forceanalog_desc)
        put("swanstation_Controller5_AnalogDPadInDigitalMode", R.string.ss_core_controller5_analogdpadindigitalmode_desc)
        put("swanstation_Controller5_AxisScale", R.string.ss_core_controller5_axisscale_desc)
        put("swanstation_Controller5_VibrationBias", R.string.ss_core_controller5_vibrationbias_desc)
        put("swanstation_Controller6_ForceAnalog", R.string.ss_core_controller6_forceanalog_desc)
        put("swanstation_Controller6_AnalogDPadInDigitalMode", R.string.ss_core_controller6_analogdpadindigitalmode_desc)
        put("swanstation_Controller6_AxisScale", R.string.ss_core_controller6_axisscale_desc)
        put("swanstation_Controller6_VibrationBias", R.string.ss_core_controller6_vibrationbias_desc)
        put("swanstation_Controller7_ForceAnalog", R.string.ss_core_controller7_forceanalog_desc)
        put("swanstation_Controller7_AnalogDPadInDigitalMode", R.string.ss_core_controller7_analogdpadindigitalmode_desc)
        put("swanstation_Controller7_AxisScale", R.string.ss_core_controller7_axisscale_desc)
        put("swanstation_Controller7_VibrationBias", R.string.ss_core_controller7_vibrationbias_desc)
        put("swanstation_Controller8_ForceAnalog", R.string.ss_core_controller8_forceanalog_desc)
        put("swanstation_Controller8_AnalogDPadInDigitalMode", R.string.ss_core_controller8_analogdpadindigitalmode_desc)
        put("swanstation_Controller8_AxisScale", R.string.ss_core_controller8_axisscale_desc)
        put("swanstation_Controller8_VibrationBias", R.string.ss_core_controller8_vibrationbias_desc)
        put("swanstation_CDROM_ReadaheadSectors", R.string.ss_core_cdrom_readaheadsectors_desc)
        put("swanstation_CPU_Overclock", R.string.ss_core_cpu_overclock_desc)
        put("swanstation_Main_ApplyGameSettings", R.string.ss_core_main_applygamesettings_desc)
        put("swanstation_Logging_LogLevel", R.string.ss_core_logging_loglevel_desc)
        put("swanstation_CPU_RecompilerICache", R.string.ss_core_cpu_recompilericache_desc)
        put("swanstation_CPU_RecompilerBlockLinking", R.string.ss_core_cpu_recompilerblocklinking_desc)
        put("swanstation_CPU_FastmemMode", R.string.ss_core_cpu_fastmemmode_desc)
        put("swanstation_CPU_FastmemRewrite", R.string.ss_core_cpu_fastmemrewrite_desc)
        put("swanstation_TextureReplacements_EnableVRAMWriteReplacements", R.string.ss_core_texturereplacements_enablevramwritereplacements_desc)
        put("swanstation_TextureReplacements_PreloadTextures", R.string.ss_core_texturereplacements_preloadtextures_desc)
        put("swanstation_Main_RunaheadFrameCount", R.string.ss_core_main_runaheadframecount_desc)
        put("swanstation_Console_Enable8MBRAM", R.string.ss_core_console_enable8mbram_desc)
        put("swanstation_Hacks_OldMDECRoutines", R.string.ss_core_hacks_oldmdecroutines_desc)
        put("swanstation_Audio_FastHook", R.string.ss_core_audio_fasthook_desc)
    }

    val choiceLabelRes: Map<String, Int> = buildMap {
        put("Auto-Detect", R.string.ss_core_choice_auto_detect)
        put("NTSC-J (Japan)", R.string.ss_core_choice_ntsc_j_japan)
        put("NTSC-U (US, Canada)", R.string.ss_core_choice_ntsc_u_us_canada)
        put("PAL (Europe, Australia)", R.string.ss_core_choice_pal_europe_australia)
        put("SCPH5500", R.string.ss_core_choice_scph5500)
        put("PSP", R.string.ss_core_choice_psp)
        put("PS3", R.string.ss_core_choice_ps3)
        put("OpenBIOS", R.string.ss_core_choice_openbios)
        put("SCPH5501", R.string.ss_core_choice_scph5501)
        put("SCPH5502", R.string.ss_core_choice_scph5502)
        put("Enabled", R.string.ss_core_choice_enabled)
        put("Disabled", R.string.ss_core_choice_disabled)
        put("None (Double Speed)", R.string.ss_core_choice_none_double_speed)
        put("2x (Quad Speed)", R.string.ss_core_choice_2x_quad_speed)
        put("3x (6x Speed)", R.string.ss_core_choice_3x_6x_speed)
        put("4x (8x Speed)", R.string.ss_core_choice_4x_8x_speed)
        put("5x (10x Speed)", R.string.ss_core_choice_5x_10x_speed)
        put("6x (12x Speed)", R.string.ss_core_choice_6x_12x_speed)
        put("7x (14x Speed)", R.string.ss_core_choice_7x_14x_speed)
        put("8x (16x Speed)", R.string.ss_core_choice_8x_16x_speed)
        put("9x (18x Speed)", R.string.ss_core_choice_9x_18x_speed)
        put("10x (20x Speed)", R.string.ss_core_choice_10x_20x_speed)
        put("Infinite/Instantaneous", R.string.ss_core_choice_infinite_instantaneous)
        put("Cached Interpreter", R.string.ss_core_choice_cached_interpreter)
        put("Hardware (Auto)", R.string.ss_core_choice_hardware_auto)
        put("Hardware (Vulkan)", R.string.ss_core_choice_hardware_vulkan)
        put("3x (for 720p)", R.string.ss_core_choice_3x_for_720p)
        put("5x (for 1080p)", R.string.ss_core_choice_5x_for_1080p)
        put("6x (for 1440p)", R.string.ss_core_choice_6x_for_1440p)
        put("9x (for 4K)", R.string.ss_core_choice_9x_for_4k)
        put("2x MSAA", R.string.ss_core_choice_2x_msaa)
        put("4x MSAA", R.string.ss_core_choice_4x_msaa)
        put("8x MSAA", R.string.ss_core_choice_8x_msaa)
        put("16x MSAA", R.string.ss_core_choice_16x_msaa)
        put("32x MSAA", R.string.ss_core_choice_32x_msaa)
        put("2x SSAA", R.string.ss_core_choice_2x_ssaa)
        put("4x SSAA", R.string.ss_core_choice_4x_ssaa)
        put("8x SSAA", R.string.ss_core_choice_8x_ssaa)
        put("16x SSAA", R.string.ss_core_choice_16x_ssaa)
        put("32x SSAA", R.string.ss_core_choice_32x_ssaa)
        put("Nearest-Neighbor", R.string.ss_core_choice_nearest_neighbor)
        put("Bilinear (No Edge Blending)", R.string.ss_core_choice_bilinear_no_edge_blending)
        put("JINC2 (No Edge Blending)", R.string.ss_core_choice_jinc2_no_edge_blending)
        put("xBR (No Edge Blending)", R.string.ss_core_choice_xbr_no_edge_blending)
        put("None", R.string.ss_core_choice_none)
        put("0.5 pixels", R.string.ss_core_choice_0_5_pixels)
        put("1.0 pixels", R.string.ss_core_choice_1_0_pixels)
        put("1.5 pixels", R.string.ss_core_choice_1_5_pixels)
        put("2.0 pixels", R.string.ss_core_choice_2_0_pixels)
        put("2.5 pixels", R.string.ss_core_choice_2_5_pixels)
        put("3.0 pixels", R.string.ss_core_choice_3_0_pixels)
        put("3.5 pixels", R.string.ss_core_choice_3_5_pixels)
        put("4.0 pixels", R.string.ss_core_choice_4_0_pixels)
        put("4.5 pixels", R.string.ss_core_choice_4_5_pixels)
        put("5.0 pixels", R.string.ss_core_choice_5_0_pixels)
        put("5.5 pixels", R.string.ss_core_choice_5_5_pixels)
        put("6.0 pixels", R.string.ss_core_choice_6_0_pixels)
        put("6.5 pixels", R.string.ss_core_choice_6_5_pixels)
        put("7.0 pixels", R.string.ss_core_choice_7_0_pixels)
        put("7.5 pixels", R.string.ss_core_choice_7_5_pixels)
        put("8.0 pixels", R.string.ss_core_choice_8_0_pixels)
        put("8.5 pixels", R.string.ss_core_choice_8_5_pixels)
        put("9.0 pixels", R.string.ss_core_choice_9_0_pixels)
        put("10.0 pixels", R.string.ss_core_choice_10_0_pixels)
        put("Corrected (NTSC)", R.string.ss_core_choice_corrected_ntsc)
        put("Corrected (Region Native)", R.string.ss_core_choice_corrected_region_native)
        put("Uncorrected (PAR 1:1)", R.string.ss_core_choice_uncorrected_par_1_1)
        put("Only Overscan Area", R.string.ss_core_choice_only_overscan_area)
        put("All Borders", R.string.ss_core_choice_all_borders)
        put("Box (Downsample 3D/Smooth All)", R.string.ss_core_choice_box_downsample_3d_smooth_all)
        put("Adaptive (Preserve 3D/Smooth 2D)", R.string.ss_core_choice_adaptive_preserve_3d_smooth_2d)
        put("Lazy (background thread, default)", R.string.ss_core_choice_lazy_background_thread_default)
        put("Enabled (block until done, like old behaviour)", R.string.ss_core_choice_enabled_block_until_done_like_old_behaviour)
        put("Disabled (compile on first use)", R.string.ss_core_choice_disabled_compile_on_first_use)
        put("Libretro (Default)", R.string.ss_core_choice_libretro_default)
        put("Shared Between All Games", R.string.ss_core_choice_shared_between_all_games)
        put("Separate Card Per Game (Game Code)", R.string.ss_core_choice_separate_card_per_game_game_code)
        put("Separate Card Per Game (Game Title)", R.string.ss_core_choice_separate_card_per_game_game_title)
        put("No Memory Card", R.string.ss_core_choice_no_memory_card)
        put("Enable on Port 1 Only", R.string.ss_core_choice_enable_on_port_1_only)
        put("Enable on Port 2 Only", R.string.ss_core_choice_enable_on_port_2_only)
        put("Enable on Ports 1 and 2", R.string.ss_core_choice_enable_on_ports_1_and_2)
        put("L1 + R1 + L3 + R3", R.string.ss_core_choice_l1_r1_l3_r3)
        put("L1 + L2 + R1 + R2 + Start + Select", R.string.ss_core_choice_l1_l2_r1_r2_start_select)
        put("L1 + R1 + Select", R.string.ss_core_choice_l1_r1_select)
        put("L1 + R1 + Start", R.string.ss_core_choice_l1_r1_start)
        put("L1 + R1 + L3", R.string.ss_core_choice_l1_r1_l3)
        put("L1 + R1 + R3", R.string.ss_core_choice_l1_r1_r3)
        put("L2 + R2 + Select", R.string.ss_core_choice_l2_r2_select)
        put("L2 + R2 + Start", R.string.ss_core_choice_l2_r2_start)
        put("L2 + R2 + L3", R.string.ss_core_choice_l2_r2_l3)
        put("L2 + R2 + R3", R.string.ss_core_choice_l2_r2_r3)
        put("L3 + R3", R.string.ss_core_choice_l3_r3)
        put("Linear", R.string.ss_core_choice_linear)
        put("Quadratic", R.string.ss_core_choice_quadratic)
        put("Cubic", R.string.ss_core_choice_cubic)
        put("Disabled (Synchronous)", R.string.ss_core_choice_disabled_synchronous)
        put("1 Sector (7KB / 2ms)", R.string.ss_core_choice_1_sector_7kb_2ms)
        put("2 Sectors (13KB / 4ms)", R.string.ss_core_choice_2_sectors_13kb_4ms)
        put("3 Sectors (20KB / 6ms)", R.string.ss_core_choice_3_sectors_20kb_6ms)
        put("4 Sectors (27KB / 8ms)", R.string.ss_core_choice_4_sectors_27kb_8ms)
        put("5 Sectors (33KB / 10ms)", R.string.ss_core_choice_5_sectors_33kb_10ms)
        put("6 Sectors (40KB / 12ms)", R.string.ss_core_choice_6_sectors_40kb_12ms)
        put("7 Sectors (47KB / 14ms)", R.string.ss_core_choice_7_sectors_47kb_14ms)
        put("8 Sectors (53KB / 16ms)", R.string.ss_core_choice_8_sectors_53kb_16ms)
        put("9 Sectors (60KB / 18ms)", R.string.ss_core_choice_9_sectors_60kb_18ms)
        put("10 Sectors (67KB / 20ms)", R.string.ss_core_choice_10_sectors_67kb_20ms)
        put("11 Sectors (73KB / 22ms)", R.string.ss_core_choice_11_sectors_73kb_22ms)
        put("12 Sectors (80KB / 24ms)", R.string.ss_core_choice_12_sectors_80kb_24ms)
        put("13 Sectors (87KB / 26ms)", R.string.ss_core_choice_13_sectors_87kb_26ms)
        put("14 Sectors (93KB / 28ms)", R.string.ss_core_choice_14_sectors_93kb_28ms)
        put("15 Sectors (100KB / 30ms)", R.string.ss_core_choice_15_sectors_100kb_30ms)
        put("16 Sectors (107KB / 32ms)", R.string.ss_core_choice_16_sectors_107kb_32ms)
        put("17 Sectors (113KB / 34ms)", R.string.ss_core_choice_17_sectors_113kb_34ms)
        put("18 Sectors (120KB / 36ms)", R.string.ss_core_choice_18_sectors_120kb_36ms)
        put("19 Sectors (127KB / 38ms)", R.string.ss_core_choice_19_sectors_127kb_38ms)
        put("20 Sectors (133KB / 40ms)", R.string.ss_core_choice_20_sectors_133kb_40ms)
        put("21 Sectors (140KB / 42ms)", R.string.ss_core_choice_21_sectors_140kb_42ms)
        put("22 Sectors (147KB / 44ms)", R.string.ss_core_choice_22_sectors_147kb_44ms)
        put("23 Sectors (153KB / 46ms)", R.string.ss_core_choice_23_sectors_153kb_46ms)
        put("24 Sectors (160KB / 48ms)", R.string.ss_core_choice_24_sectors_160kb_48ms)
        put("25 Sectors (167KB / 50ms)", R.string.ss_core_choice_25_sectors_167kb_50ms)
        put("26 Sectors (173KB / 52ms)", R.string.ss_core_choice_26_sectors_173kb_52ms)
        put("27 Sectors (180KB / 54ms)", R.string.ss_core_choice_27_sectors_180kb_54ms)
        put("28 Sectors (187KB / 56ms)", R.string.ss_core_choice_28_sectors_187kb_56ms)
        put("29 Sectors (193KB / 58ms)", R.string.ss_core_choice_29_sectors_193kb_58ms)
        put("30 Sectors (200KB / 60ms)", R.string.ss_core_choice_30_sectors_200kb_60ms)
        put("31 Sectors (207KB / 62ms)", R.string.ss_core_choice_31_sectors_207kb_62ms)
        put("32 Sectors (213KB / 64ms)", R.string.ss_core_choice_32_sectors_213kb_64ms)
        put("100% (Default)", R.string.ss_core_choice_100_default)
        put("Performance", R.string.ss_core_choice_performance)
        put("Information", R.string.ss_core_choice_information)
        put("Developer", R.string.ss_core_choice_developer)
        put("Disabled (Slower)", R.string.ss_core_choice_disabled_slower)
        put("LUT (Faster)", R.string.ss_core_choice_lut_faster)
        put("0 Frames (Disabled)", R.string.ss_core_choice_0_frames_disabled)
        put("1 Frame", R.string.ss_core_choice_1_frame)
        put("2 Frames", R.string.ss_core_choice_2_frames)
        put("3 Frames", R.string.ss_core_choice_3_frames)
        put("4 Frames", R.string.ss_core_choice_4_frames)
        put("5 Frames", R.string.ss_core_choice_5_frames)
        put("6 Frames", R.string.ss_core_choice_6_frames)
        put("7 Frames", R.string.ss_core_choice_7_frames)
        put("8 Frames", R.string.ss_core_choice_8_frames)
        put("9 Frames", R.string.ss_core_choice_9_frames)
        put("10 Frames", R.string.ss_core_choice_10_frames)
        put("Interpreter", R.string.ss_core_choice_interpreter)
        put("Recompiler", R.string.ss_core_choice_recompiler)
        put("Software", R.string.ss_core_choice_software)
        put("Bilinear", R.string.ss_core_choice_bilinear)
        put("Custom", R.string.ss_core_choice_custom)
        put("Error", R.string.ss_core_choice_error)
        put("Warning", R.string.ss_core_choice_warning)
        put("Success", R.string.ss_core_choice_success)
        put("Profile", R.string.ss_core_choice_profile)
        put("Debug", R.string.ss_core_choice_debug)
        put("Trace", R.string.ss_core_choice_trace)
    }
}
